name: 11- working pr inputs
on :
    workflow_dispatch:
        inputs:
            dry-run :
                type : boolean  # mus provide a boolean value
                description: Skip deployement and only print build output
                default : false

            target :
                type : environment  # must provide an envionment keyword : production, staging, test, ...
                required : true
                description : Which environment the workflow will target

            version :
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default : v3
                description: Release of build

jobs :
    build :
        runs-on : ubuntu-latest
        steps:
            - name : Build
              run : | 
                echo "Building with targt : ${{ inputs.version }}"
    deploy :
        runs-on : ubuntu-latest
        environment : ${{inputs.target}}
        if: ${{inputs.dry-run}}
        steps:
            - name : Deploying ...
              run : echo "Deploying to ${{inputs.target}} "