name : 13- catching 
on:
    workflow_dispatch:
        inputs:
            use-cash:
                description: whether to execute cash step
                type: boolean
                default: true
            node-version :
                description : Node version 
                type : choice
                options : 
                  - 18.x
                  - 20.x
                  - 22.x
                default : 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/my-app 
        steps :
            - name : Checkout (cloner) le projet github  # After that step, automatically we are in the project (not need to : cd <name_project)
              uses: actions/checkout@v4

            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                node-version: ${{inputs.node-version}}

            #- name : CD  ==> cette commande sera execute dans sa propre session de shell
            #  run : cd 13-caching/my-app 
            
            - name : Download cached dependencies
              uses : actions/cache@v3
              if : ${{inputs.use-cash}}
              id : cache
              with : 
                path : 13-caching/my-app/node_modules
                key : deps-node-modules-${{ hashFiles('13-caching/my-app/package-lock.json')}}

            - name : Install dependencies
              if : ${{steps.cache.outputs.cache-hit == 'false'}}
              run : npm ci

            - name : Testing
              run : npm run test

            - name : Building 
              run : npm run build

            - name : Deploying
              run : echo "Deploying to nonprod env"

# 1- Checkout github repo
# 2- install dependecies
# 3- testing
# 4- Building
# 5- Deploying in nonprod environment
              