name : 15 - matrices
on : 
    workflow_dispatch:

jobs : 
    backwards-compatibility: 
        name: ${{matrix.os}} - ${{matrix.node-version}}
        runs-on : ${{matrix.os}}
        strategy:
            fail-fast: false    # means if a job fails, other remaing jobs will not be failed 
            matrix:
                node-version : [20.x , 22.x, 24.x ]
                os : 
                    - ubuntu-latest
                    - windows-latest
                include: 
                    - os: ubuntu-latest
                      node-version: 18.x
                    - os : ubuntu-latest
                      node-version : 22.x
                      tag: experimental
        steps: 
            - name : Setup node
              uses : actions/setup-node@v6
              with : 
                node-version : ${{matrix.node-version}}
            - name : Perform some tests
              run : echo "Running tests on ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
            - name : Display experimental tag
              if : matrix.tag == 'experimental'
              run : exit 1
    
    include-example : 
        name : ${{matrix.color}} -  ${{matrix.shape}} -  ${{matrix.size}} -  ${{matrix.opacity}}
        runs-on : ubuntu-latest
        strategy:
            matrix : 
                color : [red, green, white]
                shape : [triangle, cercle]
                size : [small, large]
                include :
                    - color : red
                      shape: square
                      # opacity: 50  # this value will be added to only the one that concerned [red, square]
                    - opacity: 50 # this value will be added in each job, not only the one that concerned [red, square]
                
                exclude :  # can't exclude stuff already included 
                    - color : green
                      shape: cercle
                      size: small 
        steps : 
            - name : Dummy step
              run : echo " ${{matrix.color}} -  ${{matrix.shape}} -  ${{matrix.size}} -  ${{matrix.opacity}}"
